### ISSUE TITLE
[Bug] Space/Tab in cook.exe

### ISSUE THREAD

**Issue by RomelSan** [giteshnxtlvl/cook#10]
Command:  
`cook.exe -start first,second -end 2020,2021 start:end`  
or `cook.exe first,second:2020,2021`

Outputs:  
```
error: yaml: line 4: found character that cannot start any tokenfirst2020
first2021
second2020
second2021
```

**Comment by alanEG** [comment]
Did you set the environment variable `COOK`

**Comment by RomelSan** [comment]
![test](https://user-images.githubusercontent.com/11341002/116481766-7ee5cb00-a849-11eb-98e4-bbee9edad222.jpg)

**Comment by RomelSan** [comment]
I am not doing custom settings...
Should this work out of the box like version 1.0?
![test3](https://user-images.githubusercontent.com/11341002/116483113-1cda9500-a84c-11eb-9fb2-e2ec416e2b58.jpg)

**Comment by alanEG** [comment]
If you set the environment variable and do not restart the device,
 the variables will not be applied. 
You must restart the device
This worked for me

**Comment by RomelSan** [comment]
Pointed the COOK var to the folder (restarted and try), then to the exe file (restart and try), finally to the .yaml file and it never worked as intended... 
Will test on another computer, but for now had to add 2 lines of code (i am not a Go programmer so did the best i could).
Added to the code something like this "If there isn't a COOK env var then set the binary path as the variable".
![solution](https://user-images.githubusercontent.com/11341002/116491527-b19abe00-a85f-11eb-89b2-56096408c6f6.JPG)

**Comment by RomelSan** [comment]
@giteshnxtlvl Hi, can you add that behavior to the code?
"If there isn't a COOK env var then set the running binary path as the variable"
so it can run right out of the box too.
Thanks.

**Comment by giteshnxtlvl** [comment]
Hi @RomelSan
Just delete the env varibale COOK and cook.exe will work fine, without need of cook.yaml file.

I mentioned this in Readme before but rn it isn't there, so I will add this again.

@alanEG 
You can just restart the terminal instead of PC to get modified env variables.
Use cmder terminal it is better.

For customization
1. Create empty file `cook.yaml`
2. Set env variable COOK=pathofthisfile
3. Restart terminal and run `cook -config`

**Comment by RomelSan** [comment]
@giteshnxtlvl I think i found the bug.
cook.exe alone won't work
![error](https://user-images.githubusercontent.com/11341002/116497693-9931a000-a86d-11eb-93b1-a9242f4b0749.JPG)

You have a tab in line 49, it should be spaces.
Compiled and tested like that and it worked.
![linebug](https://user-images.githubusercontent.com/11341002/116497790-c8481180-a86d-11eb-8c3b-abca55c4a8e0.jpg)

**Comment by giteshnxtlvl** [comment]
Yes, I checked it, it's a bug. Thanks for reporting @RomelSan.
Will fix this in a minute.

**Comment by giteshnxtlvl** [comment]
Bug Fixed
