### ISSUE TITLE
issues with files option from cook.yaml

### ISSUE THREAD

**Issue by ks6274** [giteshnxtlvl/cook#11]
Hello there,
firstly, thanks a lot for the tool, i am exploring and it is really good.
However, i am facing an issue with the option of 'files'
in the cook.yaml, if i change the path of files i.e the password file from my local filesystem, then i am getting error.
example command - `cook -admin admin,root,superuser,su,sa,moderator -s "." -sep / https://mysite.com:sep:admin:robot_1000`
i am changing the location referred in the cook.yaml file to my local filesystem. When i run the above command, then i get the error `E:\tools\wordlists\SecLists\Discovery\Web-Content\RobotsDisallowed-Top1000.txt
panic: open E:\tools\wordlists\SecLists\Discovery\Web-Content\RobotsDisallowed-Top1000.txt: no such file or directory

goroutine 1 [running]:
main.fileValues(0x84c0280, 0x4e, 0xbffa46d2, 0xa, 0x84f011c)
	/home/kali/go/src/github.com/giteshnxtlvl/cook/main.go:157 +0x172
main.main()
	/home/kali/go/src/github.com/giteshnxtlvl/cook/main.go:226 +0x53b
`
i even tried changing the path in the main.go file as shown in the above error but it throws out the same error.

Can you help me on where i am messing up?? or is it an issue.

Thanks in advance.

**Comment by ks6274** [comment]
Sorry, just made some error.
followed the documentation on `cook -config` and setup custom config file.
Now works like a charm.
Thanks

**Comment by giteshnxtlvl** [comment]
Glad it work for you and you liked it :)
