### ISSUE TITLE
Support the repeater

### ISSUE THREAD

**Issue by alanEG** [giteshnxtlvl/cook#20]
hello 
Can you support an option for a loop or a repeater
example 
```
cook -start admin,root -sep -,. -end test,help start:sep:end
```
output normal 
```
admin-test
admin-help
admin.test
admin.help
root-test
root-help
root.test
root.help
```
the output can you support 
```
admin-test
admin-help
admin.test
admin.help
root-test
root-help
root.test
root.help

test-admin
test-root
test.admin
test.root
help-admin
help-root
help.admin
help.root
```
With the addition of an option for that, and not to be done automatically

**Comment by giteshnxtlvl** [comment]
Users input aren't same and netiher tool knows how user will going to use those params in the pattern.
So some option like that isn't possible.

Btw you can try this approach, some extra words in output.
```
cook -start admin,root -sep -,. -end test,help start,end:sep:end,start
```

**Comment by alanEG** [comment]
Thank you for your quick consideration of issus
This approach appears to be working
i close this issus
