### ISSUE TITLE
How to save a wordlist that has just been generated?

### ISSUE THREAD

**Issue by Skysisprod** [giteshnxtlvl/cook#22]
How to save a wordlist that has just been generated?

**Comment by alanEG** [comment]
you can use `>` or `tee`
example:
```bash
cook -username user,admin -sub @ -password password,root username:sub:password > filename
or 
cook -username user,admin -sub @ -password password,root username:sub:password | tee filename
```

**Comment by Skysisprod** [comment]
Thank you

**Comment by giteshnxtlvl** [comment]
Hey @alanEG,
Do you know why your message is not visible here?

![Screenshot (227)](https://user-images.githubusercontent.com/58145476/126866320-fa111cad-c70e-4294-a0f4-946748150230.png)

But visible in my email...
![Screenshot (226)](https://user-images.githubusercontent.com/58145476/126866281-8481925d-0080-4a1e-bffe-9945241386b3.png)

I have faced similar issues with some other messages also.

**Comment by alanEG** [comment]
Hi, after posting a comment
Because I am weak in English
I thought I might have misunderstood the problem so I deleted it

**Comment by giteshnxtlvl** [comment]
Oh! TBH your english is fine dude. No need to feel that way :)

**Comment by alanEG** [comment]
Thank you for these kind words
