### ISSUE TITLE
Ranges are not working

### ISSUE THREAD

**Issue by noraj** [giteshnxtlvl/cook#29]
Pre-defined sets are working but not ranges:

```
$ cook a-f0-9 -config-path /usr/share/cook/cook.yaml 
a-f0-9

$ cook 10-20 -config-path /usr/share/cook/cook.yaml
10-20

$ cook a-z -config-path /usr/share/cook/cook.yaml
a-z

$ cook a -config-path /usr/share/cook/cook.yaml 
a
b
c
d
e
f
g
h
i
j
k
l
m
n
o
p
q
r
s
t
u
v
w
x
y
z
```

**Comment by giteshnxtlvl** [comment]
Try cook 2.0

**Comment by noraj** [comment]
> @noraj Try cook 2.0

Yes, while troubleshooting I think I may have found wy BA package is still targeting 1.6 and not 2.0 even if we build from source (git) using the latest commit (217). I'll open a discussion for that.

**Comment by giteshnxtlvl** [comment]
Yes as you described in this issue #30. So I will let that keep active and close this one.

**Comment by noraj** [comment]
in 2.0

![image](https://user-images.githubusercontent.com/16578570/145614417-a8b4a8e6-fe86-455f-ab34-db5040c571a7.png)

So how to do `a-f0-9` or `a-n0-5` ? (I mean outside of using a defined charset like https://github.com/giteshnxtlvl/cook-ingredients/pull/2).

**Comment by giteshnxtlvl** [comment]
Depending on your needs, Use `cook 0-9 a-b` or `cook 0-9,a-b`

Logic
Separated by comma -> Same column
Separated by space -> Different columns

**Comment by noraj** [comment]
Thank you

**Comment by noraj** [comment]
If I want to generate a list from 000000 to 999999 (integers from 0 to 1M-1 with 6 digits padding).

I can do

```
cook 0-9 0-9 0-9 0-9 0-9 0-9
```

I was expecting to be able to use a repeat operator but it doesn't expand the range:

```
$ cook 0-9\*6
0-90-90-90-90-90-9
$ cook '0-9*6'
0-90-90-90-90-90-9
```

Or maybe pad the min number of the range to indicate the padding required:

```
cook 000000-999999
```

**Comment by giteshnxtlvl** [comment]
Yeah, the last one is the easiest.
Using ranges with repeat operators doesn't seem to have other use cases.
