### ISSUE TITLE
Version / release / git tags consistency 

### ISSUE THREAD

**Issue by noraj** [giteshnxtlvl/cook#31]
## Context

[I was surprise](https://github.com/BlackArch/blackarch/issues/3278) the BA [PKGBUILD for cook](https://github.com/BlackArch/blackarch/blob/master/packages/cook/PKGBUILD) was using version 1.6 and 2.0 because we are using the last commit (217) from the git source and not a specific release.

## Troubleshooting

While building the PKGBUILD manually I found that it was targeting version 1.6 (see screenshot)

![image](https://user-images.githubusercontent.com/16578570/145095358-8b5136e9-4448-4015-a00d-65891b0acb81.png)

I'm not familiar with go building process, but it seems that the following commands (https://github.com/BlackArch/blackarch/blob/cd42e3f9aa06e236bd22d18ad9a11ac5265e9895/packages/cook/PKGBUILD#L25-L34) are fetching the `@latest` release.
So I checked the [git tags here](https://github.com/giteshnxtlvl/cook/tags) and found they were inconsistent: `1.0`, `v1.5`, `v1.6.0`, `2.0.a`, `2.0`. Sometimes it using `x.y` and sometimes `x.y.z` (not following semver https://semver.org/) but more importantly sometimes it has the `v` prepended and sometimes not. So I think the go resolver find that `v1.6.0` is matching `@latest` because alphabetically `v.1.6.0` is higher than `2.0` (ASCII order).

```ruby
irb(main):001:0> ['1.0', 'v1.5', 'v1.6.0', '2.0.a', '2.0'].sort
=> ["1.0", "2.0", "2.0.a", "v1.5", "v1.6.0"]
```

### Solution A

Remove old git tags and create new git tags that all match the same versioning convention.

Example of end result:

```
1.0.0
1.5.0
1.6.0
2.0.0
2.0.0-a

# or

v1.0.0
v1.5.0
v1.6.0
v2.0.0
v2.0.0-a
```

### Solution B

If you want to keep the old references, you can create new tags following the convention with the higher precedence.

Example of end result:

```
1.0
2.0
2.0.a
v1.0.0
v1.5
v1.5.0
v1.6.0
v2.0.0
v2.0.0-a
```

About 2.0.0 and 2.0.0-a `2.0.0-a < 2.0.0` (see [semver](https://semver.org/#spec-item-11) precedence) so no worry it's not alphabetically in the right order. If you want to be extra sure make the actual `2.0` become `2.0.1`.

**Comment by giteshnxtlvl** [comment]
Thanks @noraj 
I just changed the tag to `v2.0.0`, Hope this should work.

**Comment by noraj** [comment]
Seems to point to it now:

![image](https://user-images.githubusercontent.com/16578570/145612636-91a1e52f-02cc-4a47-95ac-7e27a126d877.png)

**Comment by giteshnxtlvl** [comment]
Great! Thanks @noraj  for the solution. Nice Catch!!
