### ISSUE TITLE
Extension suggestion

### ISSUE THREAD

**Issue by Flangvik** [giteshnxtlvl/cook#6]
Tools look great, would be awesome to see a year, month, and season extension set added!

**Comment by giteshnxtlvl** [comment]
Thanks @Flangvik,
Adding **month's list** is a great idea. I will add following list in the tool.
```yaml
months : [January, February, March, April, May, June, July, August, September, October, November, December]
mon : [Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec]
```


You can print **year** directly in pattern, This will print 20XX,  
In future I am also adding ranges like [2000-2099] to make number input easy.
```
cook 20:n:n
```

Seasons list might not be useful for everyone, but you can easily add list for yourself by customzing tool Read here https://github.com/giteshnxtlvl/cook#customizing-tool

This also gives me Idea to add time and dates ranges and patterns in the tool.
Thanks :)

**Comment by Flangvik** [comment]
Awesome @giteshnxtlvl, I have to disagree on the season's list tho. When performing password spraying attacks I very often see Winter2020! Spring2021! etc. Either way great stuff!

**Comment by giteshnxtlvl** [comment]
Hi @Flangvik 
I have added lists in the new update.
I have also added 3 new features, you might like to check [Int Ranges](https://github.com/giteshnxtlvl/cook#int-ranges) and [Patterns/Functions](https://github.com/giteshnxtlvl/cook#patternsfunctions).
Please feel free to share any suggestions to add in patterns.

**Comment by Flangvik** [comment]
Awesome stuff @giteshnxtlvl, great work and keep it up! :)

**Comment by giteshnxtlvl** [comment]
Thanks @Flangvik, I am glad you like them.

**Comment by muhammedgumsay** [comment]
no problem


giteshnxtlvl ***@***.***>, 23 Nis 2021 Cum, 21:31 tarihinde
şunu yazdı:
